# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  LinterFormat:
    runs-on: ubuntu-latest
    steps:

    - name: download code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Download golangci-linter/fmt
      run : |
        # install it into ./bin/
        curl -sSfL https://golangci-lint.run/install.sh | sh -s v2.8.0
        ./bin/golangci-lint --version

      # - name: Formater
      #  run: ./bin/golangci-lint fmt
      # - name : Linter
      #  run : ./bin/golangci-lint run

    - name: Check gofmt
       run: |
         if [ -n "$(gofmt -l .)" ]; then
           echo "Go files are not formatted. Run 'gofmt -w .' to fix them."
           exit 1
         fi

        #    - name: Push the code back
        #      run: |
        #        git config user.name  "jotaalvim"
        #        git config user.email "joaoalvim179@proton.me"
        #        # Stage, Commit, and Push
        #        git add .
        #        git commit -m "style and linter"
        #        git push

    # devo usar a action oficilal do linter?
    # os commits ficam com uma descrição feia
          #golangci:
          #  name: lint
          #  runs-on: ubuntu-latest
          #  steps:
          #    - uses: actions/checkout@v5
          #    - uses: actions/setup-go@v6
          #      with:
          #        go-version: stable

          #    - name: golangci-lint
          #      uses: golangci/golangci-lint-action@v9
          #      with:
          #        version: v2.6


