# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  LinterFormat:
    runs-on: ubuntu-latest
    steps:

    - name: download code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Download golangci-linter/fmt

      run : |
        # install it into ./bin/
        curl -sSfL https://golangci-lint.run/install.sh | sh -s v2.8.0

        golangci-lint --version

    - name : Linter
      run : golangci-lint run


          #golangci:
          #  name: lint
          #  runs-on: ubuntu-latest
          #  steps:
          #    - uses: actions/checkout@v5
          #    - uses: actions/setup-go@v6
          #      with:
          #        go-version: stable

          #    - name: golangci-lint
          #      uses: golangci/golangci-lint-action@v9
          #      with:
          #        version: v2.6


